on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy over SSH and run Docker Compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Creating project folder if it doesn't exist!"
            mkdir -p /home/ubuntu
            cd /home/ubuntu

            if [ ! -d "lms/.git" ]; then
              echo "Cloning repository!" 
              git clone https://github.com/xdislom/lms.git
            else
              echo "Pulling latest changes!"
              cd    /home/ubuntu/lms
              git pull origin main  
            fi

            cd /home/ubuntu/lms/backend

            echo "Stopping containers"
            docker compose down || true

            echo "Building containers"
            docker compose build 

            echo "Running containers"
            docker compose up -d
